/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App.teacher;

import App.Student.*;
import App.AutoCompletion;
import App.DAC;
import App.EmailValidator;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Buddhika
 */
public class AddTeacher extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
        ResultSet rs2 = null;
    PreparedStatement pst2 = null;

    public AddTeacher() {
        initComponents();
        conn = DAC.ConnectDb();
      
        AutoCompletion.enable(jComboBox2);
        AutoCompletion.enable(searchCombo);
        setLocationRelativeTo(null);
        Fillcombo();FillcomboSub();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        sidTxt = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        contact = new javax.swing.JTextField();
        emailTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        fnTxt = new javax.swing.JTextField();
        jd = new com.toedter.calendar.JDateChooser();
        lnTxt = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addTxt = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        imgTxt = new javax.swing.JLabel();
        searchCombo = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 520, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 204, 0));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 640, 54));

        jLabel4.setText("TID *");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Basic Information"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Last Name");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 47, 110, 20));

        contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactActionPerformed(evt);
            }
        });
        jPanel4.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 180, -1));

        emailTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailTxtKeyReleased(evt);
            }
        });
        jPanel4.add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 180, -1));

        jLabel11.setText("Addresss");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 110, -1));

        jLabel12.setText("Date of Birth    ");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 110, -1));

        jLabel14.setText("Gender");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 110, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Male");
        jPanel4.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Female");
        jPanel4.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        jLabel19.setText("Contact No.");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 110, -1));

        jLabel36.setText("First Name *");
        jPanel4.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, 27));
        jPanel4.add(fnTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 180, -1));

        jd.setDateFormatString("yyyy-MM-dd");
        jPanel4.add(jd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 180, -1));

        lnTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnTxtActionPerformed(evt);
            }
        });
        jPanel4.add(lnTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 180, -1));

        jLabel17.setText("Email                ");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 110, -1));

        addTxt.setColumns(20);
        addTxt.setRows(5);
        jScrollPane1.setViewportView(addTxt);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 180, -1));

        jLabel7.setText("Subject");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 80, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Geo", "History", "Science", "English", " " }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 180, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Profile Picture"));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/attach.PNG"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(imgTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jButton4))
        );

        searchCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Search" }));
        searchCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                searchComboItemStateChanged(evt);
            }
        });
        searchCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sidTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(searchCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sidTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Teacher Information", jPanel1);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 610, 440));
        jTabbedPane1.getAccessibleContext().setAccessibleName("Teacher Information");

        jButton1.setText("New");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 520, -1, -1));

        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 520, 80, 30));

        jLabel1.setBackground(new java.awt.Color(255, 204, 0));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 650, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void Fillcombo() {
      //  searchCombo.removeAllItems();
        try {
             searchCombo.removeAllItems();
            searchCombo.addItem("Search");
            String sql = "SELECT * FROM teacher";
            pst2 = conn.prepareStatement(sql);
            rs2 = pst2.executeQuery();

            while (rs2.next()) {
                String name = rs2.getString("tID");
                searchCombo.addItem(name);
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            //JOptionPane.showMessageDialog(null,"Connection Disconnected, Reconnecting... Please wait..", "error", JOptionPane.ERROR_MESSAGE);
        }finally {

            try {

                rs2.close();
                pst2.close();

            } catch (Exception e) {
            }

        }

    }


private void reset(){

        sidTxt.setText(null);

        addTxt.setText(null);
        fnTxt.setText(null);
        lnTxt.setText(null);
        contact.setText(null);
        emailTxt.setText(null);
        jd.setDate(null);

        buttonGroup1.clearSelection();

      
        jComboBox2.setSelectedIndex(0);

        imgTxt.setIcon(null);
        
         
        Fillcombo();  

}

private void FillcomboSub() {
      //  searchCombo.removeAllItems();
        try {
             jComboBox2.removeAllItems();
         jComboBox2.addItem("Select");
            String sql = "SELECT * FROM subject";
            pst2 = conn.prepareStatement(sql);
            rs2 = pst2.executeQuery();

            while (rs2.next()) {
                String name = rs2.getString("name");
                jComboBox2.addItem(name);
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            //JOptionPane.showMessageDialog(null,"Connection Disconnected, Reconnecting... Please wait..", "error", JOptionPane.ERROR_MESSAGE);
        }finally {

            try {

                rs2.close();
                pst2.close();

            } catch (Exception e) {
            }

        }

    }
    private void contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactActionPerformed

    private void lnTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnTxtActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
//        // TODO add your handling code here:

        try {

            String sql = "INSERT INTO teacher(tID,fname,lname,contactno,DOB,email,gender,address,subject,image) VALUES(?,?,?,?,?,?,?,?,?,?)";

            pst = conn.prepareStatement(sql);
            pst.setString(1, sidTxt.getText());
            pst.setString(2, fnTxt.getText());
            pst.setString(3, lnTxt.getText());
            pst.setString(4, contact.getText());
            pst.setString(5, ((JTextField) jd.getDateEditor().getUiComponent()).getText());
            pst.setString(6, emailTxt.getText());
            pst.setString(7, jRadioButton1.isSelected() ? "M" : "F");
            pst.setString(8, addTxt.getText());
            pst.setString(9, jComboBox2.getSelectedItem()+ "");
           // pst.setString(10, jComboBox1.getSelectedItem().toString());
            pst.setBytes(10, person_image);

            int a = pst.executeUpdate();
            if (a > 0) {

                //  String sql2="INSERT INTO student(sID,fname,lname,contactno,DOB,email,gender,address) VALUES(?,?,?,?,?,?,?,?)";
                JOptionPane.showMessageDialog(null, "SAVED", "Successful", JOptionPane.INFORMATION_MESSAGE);
                
        Fillcombo();  
            } else {
                JOptionPane.showMessageDialog(null, "NOTSAVED", "NOTSuccessful", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception e) {
            // conn = Mysqlconnect.ConnDb();
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            //JOptionPane.showMessageDialog(null,"Connection Disconnected, Reconnecting... Please wait..", "error", JOptionPane.ERROR_MESSAGE);

        }finally {

            try {

                rs.close();
                pst.close();

            } catch (Exception e) {
            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        try {
            File image = new File(filename);
            ImageIcon image2 = new ImageIcon(filename);
            imgTxt.setIcon(image2);

            FileInputStream fis = new FileInputStream(image);

            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];

            for (int readNum; (readNum = fis.read(buf)) != -1;) {

                bos.write(buf, 0, readNum);
            }

            person_image = bos.toByteArray();
            // System.out.println(person_image+"");  
        } catch (Exception e) {

            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        sidTxt.setText(null);

        addTxt.setText(null);
        fnTxt.setText(null);
        lnTxt.setText(null);
        contact.setText(null);
        emailTxt.setText(null);
        jd.setDate(null);

        buttonGroup1.clearSelection();

      
        jComboBox2.setSelectedIndex(0);

        imgTxt.setIcon(null);
        
         
        Fillcombo();  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchComboActionPerformed

    private void searchComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_searchComboItemStateChanged

        String sql = "SELECT * FROM teacher WHERE tID=?";
        try {

            String tmp = searchCombo.getSelectedItem().toString();
            pst = conn.prepareStatement(sql);
            pst.setString(1, tmp);
            rs = (ResultSet) pst.executeQuery();
            if (rs.next()) {

                String add0 = rs.getString("tID");
                String add1 = rs.getString("fname");

                String add2 = rs.getString("lname");

                String add3 = rs.getString("contactno");
               // Date add4 = rs.getDate("DOB");
                try {
                     DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
                    Date add4 = df.parse(rs.getString("DOB"));
                      jd.setDate(add4);
                } catch (ParseException e) {
                    e.printStackTrace();
                }
                String add5 = rs.getString("email");
                String add6 = rs.getString("gender");

                String add7 = rs.getString("address");
                String add8 = rs.getString("subject");
              //  String add9 = rs.getString("div");
                

                sidTxt.setText(add0);
                fnTxt.setText(add1);
                lnTxt.setText(add2);
                contact.setText(add3);
                     // jd.setDate(add4);
                emailTxt.setText(add5);
                addTxt.setText(add7);
                
                if("M".equals(add6)){
                jRadioButton1.setSelected(true);
                }else{
                jRadioButton2.setSelected(true);
                }
                
                jComboBox2.setSelectedItem(add8);
              
  
                byte[] imagedata = rs.getBytes("image");
                format = new ImageIcon(imagedata);
                imgTxt.setIcon(format);
               // searchBar.setText("");
                // String add3=rs.getString("Emp_ID");

                // pl.setText(add3);
            }

        } catch (Exception e) {
        }finally {

            try {

                rs.close();
                pst.close();

            } catch (Exception e) {
            }

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_searchComboItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {

            String sql = "UPDATE teacher SET tID=?,fname=?,lname=?,contactno=?,DOB=?,email=?,gender=?,address=?,subject=?,image=? WHERE tID='"+searchCombo.getSelectedItem().toString()+"'";

            pst = conn.prepareStatement(sql);
            pst.setString(1, sidTxt.getText());
            pst.setString(2, fnTxt.getText());
            pst.setString(3, lnTxt.getText());
            pst.setString(4, contact.getText());
            pst.setString(5, ((JTextField) jd.getDateEditor().getUiComponent()).getText());
            pst.setString(6, emailTxt.getText());
            pst.setString(7, jRadioButton1.isSelected() ? "M" : "F");
            pst.setString(8, addTxt.getText());
            pst.setString(9, jComboBox2.getSelectedItem()+ "");
          //  pst.setString(10, jComboBox1.getSelectedItem().toString());
            pst.setBytes(10, person_image);

            int a = pst.executeUpdate();
            if (a > 0) {

                //  String sql2="INSERT INTO student(sID,fname,lname,contactno,DOB,email,gender,address) VALUES(?,?,?,?,?,?,?,?)";
                JOptionPane.showMessageDialog(null, "UPDATED", "Successful", JOptionPane.INFORMATION_MESSAGE);
              
        Fillcombo();   
            } else {
                JOptionPane.showMessageDialog(null, "NOTSAVED", "NOTSuccessful", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception e) {
            // conn = Mysqlconnect.ConnDb();
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            //JOptionPane.showMessageDialog(null,"Connection Disconnected, Reconnecting... Please wait..", "error", JOptionPane.ERROR_MESSAGE);

        }finally {

            try {

                rs.close();
                pst.close();

            } catch (Exception e) {
            }

        }
       
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void emailTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailTxtKeyReleased
EmailValidator em=new EmailValidator();

boolean yes=em.validate(emailTxt.getText());

if(yes){
 emailTxt.setBackground(new java.awt.Color(204, 255, 204));

           
}else{
 emailTxt.setBackground(new java.awt.Color(255, 204, 204));
}

// TODO add your handling code here:
    }//GEN-LAST:event_emailTxtKeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int n = JOptionPane.showConfirmDialog(null, "Confirm Delete", "", JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.YES_NO_OPTION) {

            try {

                String tmp = sidTxt.getText();
                pst = conn.prepareStatement("DELETE  FROM teacher WHERE tID =?");

                pst.setString(1, tmp);

                pst.executeUpdate();

            } catch (Exception e) {
                e.printStackTrace();
            }finally {

                try {

                    rs.close();
                    pst.close();

                } catch (Exception e) {
                }

            }
            JOptionPane.showMessageDialog(this, "Successfully Deleted");
            reset();
            
            int s = JOptionPane.showConfirmDialog(null, "Do you Want to Continue!", "", JOptionPane.YES_NO_OPTION);
            if (s == JOptionPane.YES_NO_OPTION) {
            } else {

                System.exit(0);

            }

        } else {
            JOptionPane.showMessageDialog(null, "Cancelled delete!");
            System.exit(0);
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTeacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addTxt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JTextField fnTxt;
    private javax.swing.JLabel imgTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.toedter.calendar.JDateChooser jd;
    private javax.swing.JTextField lnTxt;
    private javax.swing.JComboBox searchCombo;
    private javax.swing.JTextField sidTxt;
    // End of variables declaration//GEN-END:variables

    byte[] person_image = null;
    private ImageIcon format = null;
}
