/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App.Login;

import App.AESencrp;
import App.AutoCompletion;
import App.DAC;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Arrays;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Buddhika
 */
public class addAccounts extends javax.swing.JFrame {
String out=null;
       String EnPass;
       Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
        ResultSet rs2 = null;
    PreparedStatement pst2 = null;
    /**
     * Creates new form Home
     */
    public addAccounts() {
        initComponents();
        conn = DAC.ConnectDb();
        AutoCompletion.enable(searchCombo);
       // Fillcombo();
         setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msgLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        passTxt = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        searchCombo = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        msgLabel.setText("------");
        getContentPane().add(msgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 168, 27));

        jLabel1.setBackground(new java.awt.Color(255, 204, 0));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 358, 400, 31));

        jLabel2.setBackground(new java.awt.Color(255, 204, 0));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 400, 54));

        jLabel4.setText("Account type");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 70, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "STD", "TEA", "PRT" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 143, -1));

        jLabel5.setText("Username");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 70, 20));

        jLabel6.setText("Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 70, -1));
        getContentPane().add(passTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 143, -1));

        jButton7.setText("Generate A temporary password");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        jButton1.setText("Create Account");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 230, 30));

        searchCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        searchCombo.setEnabled(false);
        searchCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                searchComboItemStateChanged(evt);
            }
        });
        getContentPane().add(searchCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 140, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

      private String idUser(String id){
    
        String[] idS=id.split("/");
        System.out.println(idS[0]);
        
         String p2=idS[1];
         String p3=idS[2];
        out="/"+p2+"/"+p3;
         
        return(idS[0]);
        
       
    
        
    }
    
    private void Fillcombo() {
      //  searchCombo.removeAllItems(); 
        String table=null;
        String id=null;
        try {
            String Atype=jComboBox1.getSelectedItem().toString();
            
            if(   null != Atype && "Select" != Atype){ //JOptionPane.showMessageDialog(null,"correct");
                        
                if(Atype=="std" || Atype=="STD"){
                table="student";
                id="sID";
                }
                else if(Atype=="tea" || Atype=="TEA"){
                table="teacher";
                id="tID";
                }
             else if(Atype=="prt" || Atype=="PRT"){
                table="student";
                id="sID";
                }
            
         
            
            searchCombo.removeAllItems();
            searchCombo.addItem("Select");
            String sql = "SELECT * FROM '"+table+"'";
            pst2 = conn.prepareStatement(sql);
            rs2 = pst2.executeQuery();

            while (rs2.next()) {
                String name = rs2.getString(id);
                
                if(Atype=="prt" || Atype=="PRT"){
                    
                    idUser(name);
                name="PRT"+out;
                }
                
                searchCombo.addItem(name);
                
            }
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e, "Please Recheck your Inputs!", JOptionPane.ERROR_MESSAGE);
            //JOptionPane.showMessageDialog(null,"Connection Disconnected, Reconnecting... Please wait..", "error", JOptionPane.ERROR_MESSAGE);
        }finally {

            try {

                rs2.close();
                pst2.close();

            } catch (Exception e) {
            }

        }

    }
    
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

Random r = new Random();
String pass="";
    String alphabet = "123456789abcdefghijklm";
    for (int i = 0; i < 8; i++) {
       
        pass=pass+alphabet.charAt(r.nextInt(alphabet.length()));
    } 
     
passTxt.setText(pass);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
Fillcombo();        // TODO add your handling code here:
searchCombo.setEnabled(true);

    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        String sql="INSERT INTO Login(user,pass,status) VALUES(?,?,?)";
       
        
        try{
         AESencrp ePass= new AESencrp();
              EnPass=ePass.encrypt(passTxt.getText());
        
        
        pst=conn.prepareStatement(sql);
        
        pst.setString(1, searchCombo.getSelectedItem().toString());
        pst.setString(2, EnPass);
        pst.setString(3, "TRUE");
       
       pst.execute();
    
       
       
        msgLabel.setText("Successfully Created Account");
         JOptionPane.showMessageDialog(null,"Successfully Created Account ");
        
        jButton1.setEnabled(false);
        
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null,e.getMessage());
        }        finally {

            try {

                rs.close();
                pst.close();

            } catch (Exception e) {
            }

        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_searchComboItemStateChanged
         jButton1.setEnabled(true); // TODO add your handling code here:
    }//GEN-LAST:event_searchComboItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addAccounts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel msgLabel;
    private javax.swing.JTextField passTxt;
    private javax.swing.JComboBox searchCombo;
    // End of variables declaration//GEN-END:variables
}
