/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App.Login;

import App.AESencrp;
import App.DAC;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Buddhika
 */
public class firstLogin extends javax.swing.JFrame {

    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst =null;
    
    
    ResultSet rs2=null;
    PreparedStatement pst2 =null;
    
    String EnPass;
    /**
     * Creates new form firstLogin
     */
    public firstLogin() {
        initComponents();
        conn=DAC.ConnectDb();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        schTXT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        teleTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        userTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addTxt = new javax.swing.JTextArea();
        repassTxt = new javax.swing.JPasswordField();
        passTxt = new javax.swing.JPasswordField();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        imgTxt = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        msgLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "First Fill your School Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 24))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Enter School Name  :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 120, 25));

        schTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schTXTActionPerformed(evt);
            }
        });
        jPanel1.add(schTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 190, -1));

        jLabel3.setText("Address");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 120, 25));

        jLabel7.setText("Telephone");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 120, 25));
        jPanel1.add(teleTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 190, -1));

        jLabel4.setText("Username");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 120, 25));
        jPanel1.add(userTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 190, -1));

        jLabel5.setText("Create Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 120, 25));

        jLabel6.setText("Re-enter Password");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 120, 25));

        addTxt.setColumns(20);
        addTxt.setRows(5);
        jScrollPane1.setViewportView(addTxt);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 190, 80));
        jPanel1.add(repassTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 190, -1));
        jPanel1.add(passTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 190, -1));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1.setLayer(imgTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 150, 150));

        jButton3.setText("Attach");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 590, 320));

        msgLabel.setText("------");
        getContentPane().add(msgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 168, 27));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 100, 30));

        jButton2.setText("Next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 100, 30));

        jLabel8.setBackground(new java.awt.Color(255, 204, 0));
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 590, 50));

        jLabel9.setBackground(new java.awt.Color(255, 204, 0));
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        String scl=schTXT.getText();
        String address=addTxt.getText();
        String tele=teleTxt.getText();
        String username=userTxt.getText();
        String pass=passTxt.getText();
        String repass=repassTxt.getText();
        
        
        
        
         if(pass.length()>=6 || !pass.contains("")){
        
        AESencrp ePass= new AESencrp();
        
        try {
             EnPass=ePass.encrypt(pass);
        } catch (Exception ex) {
            Logger.getLogger(firstLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        if(pass == null ? repass == null : pass.equals(repass)){
            
            
            
            
            
        String sql="INSERT INTO SchoolLogin(schName,schAdd,phoneNo,user,pass,image,status) VALUES(?,?,?,?,?,?,?)";
       
        
        try{
        
        
        pst=conn.prepareStatement(sql);
        
        pst.setString(1, scl);
        pst.setString(2, address);
        pst.setString(3, tele);
        pst.setString(4, username);
        pst.setString(5, EnPass);
        pst.setBytes(6, person_image);
        pst.setString(7, "TRUE");
        
        
        
        
        
      
       pst.execute();
    
       
       
        msgLabel.setText("Added your data..");
        
        
        jButton1.setVisible(false);
        
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null,e.getMessage());
        }
        finally {

            try {

                rs.close();
                pst.close();

            } catch (Exception e) {
            }

        }
        }else{
        
            msgLabel.setText("Passwords are not matched");
        
        }
        
        
        
         }
         else{
             msgLabel.setText("Enter a Strong password");
         }
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void schTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_schTXTActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        try {
            File image = new File(filename);
            ImageIcon image2 = new ImageIcon(filename);
               imgTxt.setIcon(image2);
               
            FileInputStream fis=new FileInputStream(image);
            
            ByteArrayOutputStream bos=new ByteArrayOutputStream();
            byte[] buf=new byte[1024];
            
            for(int readNum; (readNum=fis.read(buf))!=-1;){
            
                bos.write(buf,0,readNum);
            }
            
            person_image=bos.toByteArray();
            
            
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(firstLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(firstLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(firstLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(firstLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new firstLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addTxt;
    private javax.swing.JLabel imgTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel msgLabel;
    private javax.swing.JPasswordField passTxt;
    private javax.swing.JPasswordField repassTxt;
    private javax.swing.JTextField schTXT;
    private javax.swing.JTextField teleTxt;
    private javax.swing.JTextField userTxt;
    // End of variables declaration//GEN-END:variables

private ImageIcon format=null;
byte[] person_image=null;


}
