/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App.Login;

import App.AESencrp;
import App.DAC;
import App.Home.Home;
import App.Home.HomeParent;
import App.Home.HomeStudent;
import App.Home.HomeTeacher;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Buddhika
 */
public class Login extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    String EnPass;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        conn = DAC.ConnectDb();
        setLogo();
        setLocationRelativeTo(null);
        idUser("CST/15/008");
        jPanel1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Np = new javax.swing.JPasswordField();
        ReP = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        msgTxt = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userTxt = new javax.swing.JTextField();
        passTxt = new javax.swing.JPasswordField();
        titleTxt = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        imgTxt = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Change Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18), new java.awt.Color(0, 0, 51))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jLabel5.setText("New Password                 :");

        jLabel10.setText("Re-type New Password   :");

        Np.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NpKeyReleased(evt);
            }
        });

        ReP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                RePKeyReleased(evt);
            }
        });

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Np)
                            .addComponent(ReP, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Np, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(ReP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, -1, 140));

        msgTxt.setText("--");
        getContentPane().add(msgTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 150, -1));

        jLabel8.setBackground(new java.awt.Color(255, 204, 0));
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 2, 350));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Username");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 90, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 90, 30));
        getContentPane().add(userTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 220, 30));
        getContentPane().add(passTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 220, 30));

        titleTxt.setFont(new java.awt.Font("Old English Text MT", 0, 36)); // NOI18N
        titleTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(titleTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 400, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Login");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 230, 120, 40));

        jDesktopPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));

        imgTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logotemp copy.png"))); // NOI18N

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(imgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 167, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
        );
        jDesktopPane1.setLayer(imgTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 170, 200));

        jLabel7.setBackground(new java.awt.Color(255, 204, 0));
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 30));

        jLabel9.setBackground(new java.awt.Color(255, 204, 0));
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 1060, 30));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BGlogin.PNG"))); // NOI18N
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String idUser(String id) {

        String[] idS = id.split("/");
        System.out.println(idS[0]);
        return (idS[0]);

    }
    
    
     private void resetPass() {
     
          try {
            String sql = "Select * From Login WHERE user='"+userTxt.getText()+"'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            if (rs.next()) {
 
              //status
                String status = rs.getString("status");
                System.out.println(status);
               // titleTxt.setText(title);
              //addTxt.setText(add);
                if("TRUE".equals(status)){
                System.out.println("1stTimeuser");
                  jPanel1.setVisible(true);
                  jButton1.setEnabled(false);
                }else{
                nextStep();
                
                }

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } finally {

            try {

                rs.close();
                pst.close();

            } catch (Exception e) {
            }

        }
     
     }
    
    private void nextStep() {
        if (null != idUser(userTxt.getText())) //JOptionPane.showMessageDialog(null,"correct");
        {
            switch (idUser(userTxt.getText())) {
                case "STD":
                    new HomeStudent().setVisible(true);
                    System.out.println("555");
                    break;
                case "TEA":
                    new HomeTeacher().setVisible(true);
                    break;
                case "PRT":
                    new HomeParent().setVisible(true);
                    break;

                default:
                    new Home().setVisible(true);
                    break;
            }
        }
        this.dispose();

    }

    private void setLogo() {

        try {
            String sql = "Select * From SchoolLogin WHERE status='TRUE'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            if (rs.next()) {

                byte[] imagedata = rs.getBytes("image");
                format = new ImageIcon(imagedata);
                imgTxt.setIcon(format);

                String title = rs.getString("schName");
                String add = rs.getString("schAdd");
                String pno = rs.getString("phoneNo");
                titleTxt.setText(title);
              //addTxt.setText(add);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } finally {

            try {

                rs.close();
                pst.close();

            } catch (Exception e) {
            }

        }

    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String sql = "SELECT * FROM SchoolLogin WHERE SchoolLogin.user=? AND SchoolLogin.pass=?";
        String sql2 = "SELECT * FROM Login WHERE Login.user=? AND Login.pass=?";
        try {

            AESencrp ePass = new AESencrp();
            EnPass = ePass.encrypt(passTxt.getText());

            pst = conn.prepareStatement(sql);
            pst.setString(1, userTxt.getText());
            pst.setString(2, EnPass);

            rs = pst.executeQuery();

            if (rs.next()) {

                nextStep();
                System.out.println("pstuser");
                 // JOptionPane.showMessageDialog(null,"yes");
            } else {
                rs.close();
                pst = conn.prepareStatement(sql2);
                pst.setString(1, userTxt.getText());
                pst.setString(2, EnPass);

                rs = pst.executeQuery();

                if (rs.next()) {

                   
                    //code here
                    resetPass();
                  
                    
                }else{ JOptionPane.showMessageDialog(null, "Invalid Username/Password");}
               

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } finally {

            try {

                rs.close();
                pst.close();

            } catch (Exception e) {
            }

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(Np.getText() == null ? ReP.getText() == null : Np.getText().equals(ReP.getText())){
            try {
                    
                     AESencrp ePass= new AESencrp();
               EnPass=ePass.encrypt(passTxt.getText());
                
                String sql2 = "SELECT * FROM Login WHERE user='" + userTxt.getText() + "'";
                pst =conn.prepareStatement(sql2);
                rs = pst.executeQuery();
                if (rs.next()) {
                
                   
                    String add1 = rs.getString("pass");
                    //empid.setText(add1);
                    if(add1.equals(EnPass)){
                        String sql = "UPDATE Login SET pass=?,status=? WHERE user=?";
                        rs.close();
                         String EnPass2=ePass.encrypt(ReP.getText());
                        pst = (PreparedStatement) conn.prepareStatement(sql);
                        pst.setString(1, EnPass2);
                        pst.setString(2, "FALSE");
                        pst.setString(3, userTxt.getText());
                       
                        pst.execute();

                        JOptionPane.showMessageDialog(null, "Your password has been changed", "Saved", JOptionPane.INFORMATION_MESSAGE);
                    //    Cp.setText(null);
                    //    userN.setText(null);
                        Np.setText(null);
                        ReP.setText(null);
                        nextStep();
                    }else{JOptionPane.showMessageDialog(null, "Username and Current Password are doesn't match");}

                }
                else{JOptionPane.showMessageDialog(null, "Username is incorrect");}

            } catch (SQLException | HeadlessException e) {
               // conn = Mysqlconnect.ConnDb();
                JOptionPane.showMessageDialog(null,e, "error", JOptionPane.ERROR_MESSAGE);
                // JOptionPane.showMessageDialog(null,"Connection Disconnected, Reconnecting... Please wait..", "error", JOptionPane.ERROR_MESSAGE);

            } catch (Exception ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Last two fields are not match,please check it.");

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void NpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NpKeyReleased
        if(Np.getText() == null ? ReP.getText() == null : Np.getText().equals(ReP.getText())){
            Np.setBackground(new java.awt.Color(204, 255, 204));

            ReP.setBackground(new java.awt.Color(204, 255, 204));

        }
        else{
            Np.setBackground(new java.awt.Color(255, 255, 255));

            ReP.setBackground(new java.awt.Color(255, 255, 255));
        }
    }//GEN-LAST:event_NpKeyReleased

    private void RePKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RePKeyReleased
        if(Np.getText() == null ? ReP.getText() == null : Np.getText().equals(ReP.getText())){
            Np.setBackground(new java.awt.Color(204, 255, 204));

            ReP.setBackground(new java.awt.Color(204, 255, 204));

        }
        else{
            Np.setBackground(new java.awt.Color(255, 255, 255));

            ReP.setBackground(new java.awt.Color(255, 255, 255));
        }
    }//GEN-LAST:event_RePKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Np;
    private javax.swing.JPasswordField ReP;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel imgTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel msgTxt;
    private javax.swing.JPasswordField passTxt;
    private javax.swing.JLabel titleTxt;
    private javax.swing.JTextField userTxt;
    // End of variables declaration//GEN-END:variables
private ImageIcon format = null;
}
