/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App.Message;

import App.AutoCompletion;
import App.DAC;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Buddhika
 */
public class postNews extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    ResultSet rs2 = null;
    PreparedStatement pst2 = null;

    public postNews() {
        initComponents();
        this.setLocationRelativeTo(null);
        conn = DAC.ConnectDb();
       // AutoCompletion.enable(jComboBox1);
        // AutoCompletion.enable(jComboBox2);
        AutoCompletion.enable(searchCombo);

        Fillcombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        sidTxt = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jd = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        addTxt = new javax.swing.JTextArea();
        searchCombo = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 204, 0));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 640, 54));

        jLabel4.setText("Title");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Information"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setText("News Content");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 110, -1));

        jLabel12.setText("Date");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, -1));

        jd.setDateFormatString("yyyy-MM-dd");
        jPanel4.add(jd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 180, -1));

        addTxt.setColumns(20);
        addTxt.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        addTxt.setRows(5);
        jScrollPane1.setViewportView(addTxt);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 250, 270));

        searchCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Search" }));
        searchCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                searchComboItemStateChanged(evt);
            }
        });
        searchCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sidTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(searchCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sidTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("news", jPanel1);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 610, 440));
        jTabbedPane1.getAccessibleContext().setAccessibleName("news Information");

        jButton1.setText("New");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 520, -1, -1));

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 520, -1, -1));

        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 520, 80, 30));

        jLabel1.setBackground(new java.awt.Color(255, 204, 0));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 650, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void Fillcombo() {
        //  searchCombo.removeAllItems();
        try {
            searchCombo.removeAllItems();
            searchCombo.addItem("Select");
            String sql = "SELECT * FROM news";
            pst2 = conn.prepareStatement(sql);
            rs2 = pst2.executeQuery();

            while (rs2.next()) {
                String name = rs2.getString("title");
                searchCombo.addItem(name);
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            //JOptionPane.showMessageDialog(null,"Connection Disconnected, Reconnecting... Please wait..", "error", JOptionPane.ERROR_MESSAGE);
        }finally {

            try {

                rs2.close();
                pst2.close();

            } catch (Exception e) {
            }

        }

    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
//        // TODO add your handling code here:

        try {

            String sql = "INSERT INTO news(title,date,news) VALUES(?,?,?)";

            pst = conn.prepareStatement(sql);
            pst.setString(1, sidTxt.getText());
          //  pst.setString(2, fnTxt.getText());
            // pst.setString(3, lnTxt.getText());
            // pst.setString(4, contact.getText());
            pst.setString(2, ((JTextField) jd.getDateEditor().getUiComponent()).getText());
           // pst.setString(6, emailTxt.getText());
            // pst.setString(7, jRadioButton1.isSelected() ? "M" : "F");
            pst.setString(3, addTxt.getText());

            int a = pst.executeUpdate();
            if (a > 0) {

                Fillcombo();
                //  String sql2="INSERT INTO student(sID,fname,lname,contactno,DOB,email,gender,address) VALUES(?,?,?,?,?,?,?,?)";
                JOptionPane.showMessageDialog(null, "SAVED", "Successful", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "NOTSAVED", "NOTSuccessful", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception e) {
            // conn = Mysqlconnect.ConnDb();
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            //JOptionPane.showMessageDialog(null,"Connection Disconnected, Reconnecting... Please wait..", "error", JOptionPane.ERROR_MESSAGE);

        }finally {

            try {

                rs.close();
                pst.close();

            } catch (Exception e) {
            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Fillcombo();

        sidTxt.setText(null);

        addTxt.setText(null);

        jd.setDate(null);

        buttonGroup1.clearSelection();


    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchComboActionPerformed

    private void searchComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_searchComboItemStateChanged

        String sql = "SELECT * FROM news WHERE title=?";
        try {

            String tmp = searchCombo.getSelectedItem().toString();
            pst = conn.prepareStatement(sql);
            pst.setString(1, tmp);
            rs = (ResultSet) pst.executeQuery();
            if (rs.next()) {

                String add0 = rs.getString("title");

               
                try {
                     DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
                    Date add4 = df.parse(rs.getString("date"));
                      jd.setDate(add4);
                } catch (ParseException e) {
                    e.printStackTrace();
                }

          
                String add7 = rs.getString("news");

               // System.out.println(add4);
                sidTxt.setText(add0);
             //   fnTxt.setText(add1);
                //  lnTxt.setText(add2);
                //  contact.setText(add3);
             
                // emailTxt.setText(add5);
                addTxt.setText(add7);

            }

        } catch (Exception e) {
        }finally {

            try {

                rs.close();
                pst.close();

            } catch (Exception e) {
            }

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_searchComboItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {

            String sql = "UPDATE news SET title=?,date=?,news=? WHERE title='" + searchCombo.getSelectedItem().toString() + "'";

            pst = conn.prepareStatement(sql);
            pst.setString(1, sidTxt.getText());

            pst.setString(2, ((JTextField) jd.getDateEditor().getUiComponent()).getText());

            pst.setString(3, addTxt.getText());

            int a = pst.executeUpdate();
            if (a > 0) {

                //  String sql2="INSERT INTO student(sID,fname,lname,contactno,DOB,email,gender,address) VALUES(?,?,?,?,?,?,?,?)";
                JOptionPane.showMessageDialog(null, "UPDATED", "Successful", JOptionPane.INFORMATION_MESSAGE);

                Fillcombo();
            } else {
                JOptionPane.showMessageDialog(null, "NOTSAVED", "NOTSuccessful", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception e) {
            // conn = Mysqlconnect.ConnDb();
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            //JOptionPane.showMessageDialog(null,"Connection Disconnected, Reconnecting... Please wait..", "error", JOptionPane.ERROR_MESSAGE);

        }finally {

            try {

                rs.close();
                pst.close();

            } catch (Exception e) {
            }

        }


    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(postNews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(postNews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(postNews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(postNews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new postNews().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addTxt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.toedter.calendar.JDateChooser jd;
    private javax.swing.JComboBox searchCombo;
    private javax.swing.JTextField sidTxt;
    // End of variables declaration//GEN-END:variables

}
