/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App.Message;

import App.AutoCompletion;
import App.DAC;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;

/**
 *
 * @author Buddhika
 */
public class sendMsg extends javax.swing.JFrame {
String out=null;
       String EnPass;
       Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
        ResultSet rs2 = null;
    PreparedStatement pst2 = null;
    /**
     * Creates new form Home
     */
    public sendMsg() {
        initComponents();
        conn = DAC.ConnectDb();
        AutoCompletion.enable(searchCombo);
       // Fillcombo();
         setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msgLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        searchCombo = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();
        subj = new javax.swing.JTextField();
        sub = new javax.swing.JLabel();
        sub1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        msgLabel.setText("------");
        getContentPane().add(msgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 168, 27));

        jLabel1.setBackground(new java.awt.Color(255, 204, 0));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 410, 31));

        jLabel2.setBackground(new java.awt.Color(255, 204, 0));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 54));

        jLabel4.setText("Account type");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 70, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "STD", "TEA", "PRT" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 143, -1));

        jLabel5.setText("Username");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 70, 20));

        jButton1.setText("Send");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 120, 30));

        searchCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        searchCombo.setEnabled(false);
        searchCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                searchComboItemStateChanged(evt);
            }
        });
        getContentPane().add(searchCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 140, -1));

        text.setBackground(new java.awt.Color(204, 204, 204));
        text.setColumns(20);
        text.setRows(5);
        jScrollPane2.setViewportView(text);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 270, 150));

        subj.setBackground(new java.awt.Color(204, 204, 204));
        subj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjActionPerformed(evt);
            }
        });
        getContentPane().add(subj, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 210, -1));

        sub.setText("Message   :");
        getContentPane().add(sub, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 60, 30));

        sub1.setText("Subject   :");
        getContentPane().add(sub1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 60, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

      private String idUser(String id){
    
        String[] idS=id.split("/");
        System.out.println(idS[0]);
        
         String p2=idS[1];
         String p3=idS[2];
        out="/"+p2+"/"+p3;
         
        return(idS[0]);
        
       
    
        
    }
      void send(String Subject,String msg_content,String recever){
      
        
        Properties props= new Properties();
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.socketFactory.port ", "465");
        props.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.port", "465");
        
        Session session = Session.getDefaultInstance(props,
                new javax.mail.Authenticator(){
                @Override
                protected javax.mail.PasswordAuthentication getPasswordAuthentication(){
                return new javax.mail.PasswordAuthentication("careerbuildersys@gmail.com","careerbuilder");
                }             
                }
                
                );
        try{
        Message message =new MimeMessage(session);
        message.setFrom(new InternetAddress("careerbuildersys@gmail.com"));
        message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(recever));
        message.setSubject(Subject);
        message.setText(msg_content);
        Transport.send(message);
        JOptionPane.showMessageDialog(null, "message sent");
        }
        catch(MessagingException | HeadlessException e){
        JOptionPane.showMessageDialog(null, e.getMessage());
        }
      }
    
    private void Fillcombo() {
      //  searchCombo.removeAllItems(); 
        String table=null;
        String id=null;
        try {
            String Atype=jComboBox1.getSelectedItem().toString();
            
            if(   null != Atype && "Select" != Atype){ //JOptionPane.showMessageDialog(null,"correct");
                        
                if(Atype=="std" || Atype=="STD"){
                table="student";
                id="sID";
                }
                else if(Atype=="tea" || Atype=="TEA"){
                table="teacher";
                id="tID";
                }
             else if(Atype=="prt" || Atype=="PRT"){
                table="student";
                id="sID";
                }
            
         
            
            searchCombo.removeAllItems();
            searchCombo.addItem("Select");
            String sql = "SELECT * FROM '"+table+"'";
            pst2 = conn.prepareStatement(sql);
            rs2 = pst2.executeQuery();

            while (rs2.next()) {
                String name = rs2.getString(id);
                
                if(Atype=="prt" || Atype=="PRT"){
                    
                    idUser(name);
                name="PRT"+out;
                }
                
                searchCombo.addItem(name);
                
            }
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            //JOptionPane.showMessageDialog(null,"Connection Disconnected, Reconnecting... Please wait..", "error", JOptionPane.ERROR_MESSAGE);
        }finally {

            try {

                rs2.close();
                pst2.close();

            } catch (Exception e) {
            }

        }

    }
    
    
    
    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
Fillcombo();        // TODO add your handling code here:
searchCombo.setEnabled(true);

    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//select q user id and get email.. then call to send() funtion
      try {

            String sql = "SELECT * FROM student WHERE sID='" + searchCombo.getSelectedItem().toString()+ "'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            if(rs.next()){
            
            String id=rs.getString("email");
                System.out.println(id);
                
                send(subj.getText(),text.getText(),id);
            }
           // System.out.println(sql);
            // JOptionPane.showMessageDialog(null, "Send", "error", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            //JOptionPane.showMessageDialog(null,"Connection Disconnected, Reconnecting... Please wait..", "error", JOptionPane.ERROR_MESSAGE);

        } finally {

            try {

                rs.close();
                pst.close();

            } catch (Exception e) {
            }

        }  
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_searchComboItemStateChanged
         jButton1.setEnabled(true); // TODO add your handling code here:
    }//GEN-LAST:event_searchComboItemStateChanged

    private void subjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sendMsg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sendMsg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sendMsg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sendMsg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sendMsg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel msgLabel;
    private javax.swing.JComboBox searchCombo;
    private javax.swing.JLabel sub;
    private javax.swing.JLabel sub1;
    private javax.swing.JTextField subj;
    private javax.swing.JTextArea text;
    // End of variables declaration//GEN-END:variables
}
